### ISSUE TITLE
Error with dashboard and tile editors

### ISSUE THREAD

**Issue by fabiovin** [bryan2894-playgrnd/SimpleWear#28] opened 2023-09-06 09:20 UTC
With the latest version, I'm no longer able to edit the dashboard and the tile.

After making changes and clicking the "Save" button the application is closed and the changes are not applied.

![IMG_20230906_110903](https://github.com/SimpleAppProjects/SimpleWear/assets/46569952/6aa5dd69-f48e-401f-833c-a7fd8a738e30)

Oppo Reno 6 Pro (Androind 13 - ColorOS 13.1) -  Fossil Gen 6 (WearOS 3)

**Comment by thewizrd** [comment] 2023-09-06 15:21
Hello,
This should be fixed with the latest update (1.13.0) which is rolling out. Please let me know if you are still facing issues.

**Comment by fabiovinci** [comment] 2023-09-10 14:46
Dear @thewizrd,

thank you for your reply.
I confirm that the issue is solved by the latest release.

**Comment by thewizrd** [comment] 2023-09-24 04:06
Resolved: https://github.com/SimpleAppProjects/SimpleWear/commit/32470cd3bc2464f732f48cb82975563aa3ca062b

**Closed as completed by thewizrd** 2023-09-24 04:06 UTC
